thruster_1_controller:
  type: velocity_controllers/JointVelocityController
  joint:  prop_1_to_thruster_1_joint
thruster_2_controller:
  type: velocity_controllers/JointVelocityController
  joint: prop_2_to_thruster_2_joint
thruster_3_controller:
  type: velocity_controllers/JointVelocityController
  joint: prop_3_to_thruster_3_joint
thruster_4_controller:
  type: velocity_controllers/JointVelocityController
  joint: prop_4_to_thruster_4_joint
thruster_5_controller:
   type: velocity_controllers/JointVelocityController
   joint: prop_5_to_thruster_5_joint
thruster_6_controller:
   type: velocity_controllers/JointVelocityController
   joint: prop_6_to_thruster_6_joint
thruster_7_controller:
   type: velocity_controllers/JointVelocityController
   joint: prop_7_to_thruster_7_joint
thruster_8_controller:
   type: velocity_controllers/JointVelocityController
   joint: prop_8_to_thruster_8_joint   

# /gazebo_ros_control:   
#   pid_gains:
#     prop_1_to_thruster_1_joint:
#       p: 100.0
#       i: 0.01 
#       d: 10.0

#     prop_2_to_thruster_2_joint:
#       p: 100.0
#       i: 0.01 
#       d: 10.0

#     prop_3_to_thruster_3_joint:
#       p: 100.0
#       i: 0.01 
#       d: 10.0

#     prop_4_to_thruster_4_joint:
#       p: 100.0
#       i: 0.01 
#       d: 10.0